version: '1.0'

services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - network

  migrator:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: migrate
    networks:
      - network
    depends_on:
      - backend

  seeder:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: db:seed
    networks:
      - network
    depends_on:
      - backend
      - migrator

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: serve --port=8080 --host=0.0.0.0
    ports:
      - "8080:8080"
    networks:
      - network
    depends_on:
      - db

  queue:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: queue:work
    networks:
      - network
    depends_on:
      - backend
      - migrator

volumes:
  postgres_data:

networks:
  network:
    driver: bridge